name: CI/CD Test

on:
  push:
    branches: [ "main" ]

jobs:
  api_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Newman
        run: npm install -g newman

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./WTP-main

      - name: Build Project
        run: dotnet build --no-restore
        working-directory: ./WTP-main

      - name: Start server
        run: nohup dotnet run &
        working-directory: ./WTP-main/server

      - name: Run API Tests
        run: newman run ./Postman/WTP_Test.postman_collection.json

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./WTP-main

    - name: Build Playwright tests
      run: dotnet build
      working-directory: ./END2ENDTester

    - name: Install Playwright browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      working-directory: ./END2ENDTester

    - name: Install xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Start server
      run: nohup dotnet run &
      working-directory: ./WTP-main/server

    - name: Install client dependencies
      run: npm install
      working-directory: ./WTP-main/client

    - name: Install wait-on
      run: npm install wait-on
      working-directory: ./WTP-main/client

    - name: Start client
      run: nohup npm run dev -- --host --port 3002 &
      working-directory: ./WTP-main/client

    - name: Wait for client to be ready
      run: npx wait-on -t 60000 http://localhost:3002 sleep 15
      working-directory: ./WTP-main/client

    - name: Run GUI Tests (with xvfb)
      run: xvfb-run --auto-servernum -- dotnet test
      working-directory: ./END2ENDTester


  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [api_tests, gui_tests]

    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /srv/www/malmo/martin
            git clone https://github.com/Hultberg80/WTP-Test.git
